name: cekongkir
version: 1.0.0+1
publish_to: none
description: Shipping Cost Checker
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  dropdown_search: 5.0.5
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - .env


