name: postage_checker
version: 1.0.0
publish_to: none
description: Postage Checker
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  http: 0.13.5
  dropdown_search: 5.0.5
  flutter_dotenv: ^5.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

assets:
  - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
